# Site settings
title: ChampGG
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://champ.gg" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
